export const LOCALIZATION = {
  ru: {
    name: 'Дмитрий Каракулько',
    specialization: 'Фронт-енд Разработчик',
    aboutMe: `Крайне заинтересован в направлении Фронт-енд разработки, так как считаю, что
    разработка качественного пользовательского интерфейса, улучшение пользовательского опыта - являются ключевыми
    источники успеха для любого веб-приложения.`,
    notFound: 'Не найдено',
    resourseRequest: 'Запрашиваемый ресурс не найден!',
    getIn: 'Свяжитесь',
    touch: 'Со Мной',
    contacts: 'Контакты',
    about: 'Обо',
    me: 'Мне',
    myE: 'Моё',
    myI: 'Мои',
    portfolio: 'Портфолио',
    works: 'Работы',
    certificates: 'Сертификаты',
    awards: 'Награды',
    resume: 'Резюме',
    deploy: 'Деплой',
    code: 'Код',
    link: 'Ссылка',
    title: 'Название',
    stack: 'Стек',
    electronicForm: 'Электронный вид',
    self: 'Само',
    introduction: 'Презентация',
  },
  en: {
    name: 'Dzmitry Karakulka',
    specialization: 'Front-end Developer',
    aboutMe: `Extremely interested in the direction of Front-end development, as I believe that the
    development of a high-quality user interface, improving user experience - are the key
    sources of success for any web application.`,
    notFound: 'Not Found',
    resourseRequest: 'The resourse requested could not be found!',
    getIn: 'Get In',
    touch: 'Touch',
    contacts: 'Contacts',
    about: 'About',
    me: 'Me',
    myE: 'My',
    myI: 'My',
    portfolio: 'Portfolio',
    works: 'Works',
    certificates: 'Certificates',
    awards: 'Awards',
    resume: 'Resume',
    deploy: 'Deploy',
    code: 'Code',
    link: 'Link',
    title: 'Title',
    stack: 'Stack',
    electronicForm: 'Electronic Form',
    self: 'Self',
    introduction: 'Introduction',
  },
};
